name = "WebDisplay"
uuid = "dddeb75b-f881-5cc0-ac7d-70edf6a556f0"
author = ["Zhang Shiwei <ylxdzsw@gmail.com>"]
version = "1.0.0-rc"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Restful = "a0979ab6-dee4-51c8-812d-69046455aaa6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
